/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.ConexaoDB;
import controler.ControleUsuario;
import static java.awt.SystemColor.control;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.ModelTable;
import model.ModelUsuario;

/**
 *
 * @author renato
 */
public class CadastroUsuario extends javax.swing.JFrame {

    ModelUsuario modu = new ModelUsuario();
    ControleUsuario daou = new ControleUsuario();
     
    ConexaoDB conecta = new ConexaoDB();//variavel global
    
    int flag = 0;
    
    public CadastroUsuario() {
        initComponents();
        preencherTabela("select *from usuarios order by nome_usuario");
//preenche em ordem alfabetica
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtCadastroUsuario = new javax.swing.JTextField();
        jtSenhaUsuario = new javax.swing.JPasswordField();
        jtConfirmaSenha = new javax.swing.JPasswordField();
        jbNovoUsuario = new javax.swing.JButton();
        jbAlterarUsuario = new javax.swing.JButton();
        jbSalvarUsuario = new javax.swing.JButton();
        jbExcluirUsuario = new javax.swing.JButton();
        jbCancelarUsuario = new javax.swing.JButton();
        jtPesquisaUsuario = new javax.swing.JTextField();
        jbPesquisarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jcTipoUsuario = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtIDCadastroUser = new javax.swing.JTextField();
        jbCadastroVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Usuário");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Senha:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Usuário:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Confirmar Senha:");

        jtCadastroUsuario.setEnabled(false);
        jtCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCadastroUsuarioActionPerformed(evt);
            }
        });

        jtSenhaUsuario.setEnabled(false);

        jtConfirmaSenha.setEnabled(false);

        jbNovoUsuario.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jbNovoUsuario.setText("Novo");
        jbNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoUsuarioActionPerformed(evt);
            }
        });

        jbAlterarUsuario.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jbAlterarUsuario.setText("Alterar");
        jbAlterarUsuario.setEnabled(false);
        jbAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarUsuarioActionPerformed(evt);
            }
        });

        jbSalvarUsuario.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jbSalvarUsuario.setText("Salvar");
        jbSalvarUsuario.setEnabled(false);
        jbSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarUsuarioActionPerformed(evt);
            }
        });

        jbExcluirUsuario.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jbExcluirUsuario.setText("Excluir");
        jbExcluirUsuario.setEnabled(false);
        jbExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirUsuarioActionPerformed(evt);
            }
        });

        jbCancelarUsuario.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jbCancelarUsuario.setText("Cancelar");
        jbCancelarUsuario.setEnabled(false);
        jbCancelarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarUsuarioActionPerformed(evt);
            }
        });

        jbPesquisarUsuario.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jbPesquisarUsuario.setText("Pesquisar");
        jbPesquisarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarUsuarioActionPerformed(evt);
            }
        });

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuario);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Tipo:");

        jcTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "funcionario(usuario)", " " }));
        jcTipoUsuario.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Cod.:");

        jtIDCadastroUser.setEnabled(false);
        jtIDCadastroUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIDCadastroUserActionPerformed(evt);
            }
        });

        jbCadastroVoltar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jbCadastroVoltar.setText("Voltar");
        jbCadastroVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCadastroVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtSenhaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(jtCadastroUsuario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtPesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jbNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jbSalvarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jbCancelarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(39, 39, 39)
                                        .addComponent(jtIDCadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(89, 89, 89)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcTipoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbPesquisarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jbAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtIDCadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jcTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jtSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisarUsuario))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovoUsuario)
                    .addComponent(jbSalvarUsuario)
                    .addComponent(jbCancelarUsuario)
                    .addComponent(jbAlterarUsuario)
                    .addComponent(jbExcluirUsuario))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbCadastroVoltar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(700, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCadastroUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCadastroUsuarioActionPerformed

    private void jbNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoUsuarioActionPerformed
        
       flag=1; 
       jtCadastroUsuario.setEnabled(true);
       jcTipoUsuario.setEnabled(true);
       jtSenhaUsuario.setEnabled(true);
       jtConfirmaSenha.setEnabled(true);
       jbSalvarUsuario.setEnabled(true);
       
       jbCancelarUsuario.setEnabled(true);
       
   
    }//GEN-LAST:event_jbNovoUsuarioActionPerformed

    private void jbSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarUsuarioActionPerformed
    
if(jtCadastroUsuario.getText().isEmpty()){

    JOptionPane.showMessageDialog(null, "Preencha o USUÁRIO para continuar");
    
    jtCadastroUsuario.requestFocus();//vai direto para nome
}else if(jtSenhaUsuario.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Preencha a SENHA para continuar");
    
    jtSenhaUsuario.requestFocus(); //vai direto para telefone 

}else if(jtConfirmaSenha.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Preencha o Confirmar Senha para continuar");
    
    jtConfirmaSenha.requestFocus();}
else if(jtSenhaUsuario.getText().equals(jtConfirmaSenha.getText())){
        if(flag == 1){//update com dados alterados
        modu.setUsuNome(jtCadastroUsuario.getText());
        modu.setUsoTipo((String) jcTipoUsuario.getSelectedItem());
        modu.setUsoSenha(jtSenhaUsuario.getText());
        
        daou.Salvar(modu);
       //limoa as areas de texto:
        jtSenhaUsuario.setText("");
        jtConfirmaSenha.setText("");
        jtCadastroUsuario.setText("");
        //jtIDCadastroUser.setText("");
        
        //bloqueia areas de texto:
        jtCadastroUsuario.setEnabled(false);
        jtSenhaUsuario.setEnabled(false);
        jtConfirmaSenha.setEnabled(false);
        jcTipoUsuario.setEnabled(false);
        jbSalvarUsuario.setEnabled(false);
        preencherTabela("select *from usuarios order by nome_usuario");
        
}else {
       
        modu.setUsoCod((Integer.parseInt(jtIDCadastroUser.getText())));
        modu.setUsuNome(jtCadastroUsuario.getText());
        modu.setUsoTipo((String) jcTipoUsuario.getSelectedItem());
        modu.setUsoSenha(jtSenhaUsuario.getText());
        
        daou.Alterar(modu); 
        
         jtSenhaUsuario.setText("");
        jtConfirmaSenha.setText("");
        jtCadastroUsuario.setText("");
        
        //bloqueia areas de texto:
        jtCadastroUsuario.setEnabled(false);
        jtSenhaUsuario.setEnabled(false);
        jtConfirmaSenha.setEnabled(false);
        jcTipoUsuario.setEnabled(false);
        jbSalvarUsuario.setEnabled(false);
        
        preencherTabela("select *from usuarios order by nome_usuario");
        
            }
        }else{
                JOptionPane.showMessageDialog(rootPane, "As senhas não Correspondem");
                }   
    }//GEN-LAST:event_jbSalvarUsuarioActionPerformed

    private void jbPesquisarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarUsuarioActionPerformed
        
        
            
        modu.setUsuPesquisar(jtPesquisaUsuario.getText());
        ModelUsuario model = daou.buscaUsuario(modu);//envia por parametro o que o usuario digitou
         jtIDCadastroUser.setText(String.valueOf(model.getUsoCod()));
        jtCadastroUsuario.setText(model.getUsuNome());
        jtSenhaUsuario.setText(model.getUsoSenha());
        jtConfirmaSenha.setText(model.getUsoSenha());
        jcTipoUsuario.setSelectedItem(model.getUsoTipo());
        jbAlterarUsuario.setEnabled(true);
       jbExcluirUsuario.setEnabled(true);
        
        preencherTabela("select *from usuarios where nome_usuario like'%" + modu.getUsuPesquisar()+ "%'");
        
        
    }//GEN-LAST:event_jbPesquisarUsuarioActionPerformed

    private void jbAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarUsuarioActionPerformed
      
        flag = 2;
        
       jtCadastroUsuario.setEnabled(true);
       jcTipoUsuario.setEnabled(true);
       jtSenhaUsuario.setEnabled(true);
       jtConfirmaSenha.setEnabled(true);
       jbSalvarUsuario.setEnabled(true);
       jbCancelarUsuario.setEnabled(true);
       
   
        
        
    }//GEN-LAST:event_jbAlterarUsuarioActionPerformed

    private void jbExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirUsuarioActionPerformed
       
        
        int resposta = 0;//guarda resposta do usuario
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente Excluir ?");
        if(resposta == JOptionPane.YES_OPTION){
            modu.setUsoCod(Integer.parseInt(jtIDCadastroUser.getText()));
            daou.Excluir(modu);
            
            
             
         jtIDCadastroUser.setText("");
    jtCadastroUsuario.setText("");
    jtConfirmaSenha.setText("");
    jtSenhaUsuario.setText("");
    jtPesquisaUsuario.setText("");
    
    preencherTabela("select *from usuarios order by nome_usuario");
    
        }
        
        
        
    }//GEN-LAST:event_jbExcluirUsuarioActionPerformed

    private void jtIDCadastroUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIDCadastroUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIDCadastroUserActionPerformed

    private void jbCancelarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarUsuarioActionPerformed
         jtCadastroUsuario.setEnabled(false);
        jtSenhaUsuario.setEnabled(false);
        jtConfirmaSenha.setEnabled(false);
        jcTipoUsuario.setEnabled(false);
        jbSalvarUsuario.setEnabled(false);
        jbCancelarUsuario.setEnabled(false);
        jbAlterarUsuario.setEnabled(false);
        jbExcluirUsuario.setEnabled(false);
        jtCadastroUsuario.setText("");
        jtIDCadastroUser.setText("");
        jtSenhaUsuario.setText("");
        
    }//GEN-LAST:event_jbCancelarUsuarioActionPerformed

    private void jTableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuarioMouseClicked
                String nome_usuario ="" + jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 1);//pega valores da tabela;
               conecta.conexao();
               conecta.executaSql("select *from usuarios where nome_usuario='" + nome_usuario +"'");   
        
        try {
              
               conecta.rs.first();
               jtSenhaUsuario.setText(String.valueOf(conecta.rs.getInt("senha_usuario")));
               jtCadastroUsuario.setText(conecta.rs.getString("nome_usuario"));
               jtConfirmaSenha.setText(String.valueOf(conecta.rs.getInt("senha_usuario")));
               jtIDCadastroUser.setText(String.valueOf(conecta.rs.getInt("cod_usuario")));
               
               
               
           } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, "Erro ao selecionar dados" + ex);
           }

conecta.desconecta();
jbAlterarUsuario.setEnabled(true);
jbExcluirUsuario.setEnabled(true);
jbCancelarUsuario.setEnabled(true);

      
       
    }//GEN-LAST:event_jTableUsuarioMouseClicked

    private void jbCadastroVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroVoltarActionPerformed
         TelaPrincipal telacad = new TelaPrincipal();
      
        telacad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbCadastroVoltarActionPerformed

     public void preencherTabela(String Sql){
       ArrayList dados = new ArrayList();
       String [] colunas = new String []{"ID","Nome Usuario","Senha Usuário","Tipo Usuario"};
        conecta.conexao();
        conecta.executaSql(Sql);
        
        try{
            conecta.rs.first();
            do{
                dados.add(new Object[]{conecta.rs.getInt("cod_usuario"),conecta.rs.getString("nome_usuario"),conecta.rs.getString("senha_usuario"),conecta.rs.getString("tipo_usuario")});
            }while(conecta.rs.next());
        }catch (SQLException ex){
           JOptionPane.showMessageDialog(rootPane,"Busque Novamente "+ex.getMessage()); 
        }
        ModelTable modelo = new ModelTable(dados, colunas);
        jTableUsuario.setModel(modelo);
        jTableUsuario.getColumnModel().getColumn(0).setPreferredWidth(32);
        jTableUsuario.getColumnModel().getColumn(0).setResizable(false);//usuario n pode aumentar tamanho da coluna
        
        jTableUsuario.getColumnModel().getColumn(1).setPreferredWidth(240);
        jTableUsuario.getColumnModel().getColumn(1).setResizable(false);//usuario n pode aumentar nome na coluna
       
       jTableUsuario.getColumnModel().getColumn(2).setPreferredWidth(120);
       jTableUsuario.getColumnModel().getColumn(2).setResizable(false);//usuario n pode aumentar telefone da coluna
       
        jTableUsuario.getColumnModel().getColumn(3).setPreferredWidth(220);
        jTableUsuario.getColumnModel().getColumn(3).setResizable(false);//usuario n pode aumentar endereco da coluna
       
       jTableUsuario.getTableHeader().setReorderingAllowed(false);
       jTableUsuario.setAutoResizeMode(jTableUsuario.AUTO_RESIZE_OFF);//nao pode redimencionar tabela;
        
        jTableUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//seleciona apenas um por vez na tabela
        
        
        conecta.desconecta();
        
    }
    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JButton jbAlterarUsuario;
    private javax.swing.JButton jbCadastroVoltar;
    private javax.swing.JButton jbCancelarUsuario;
    private javax.swing.JButton jbExcluirUsuario;
    private javax.swing.JButton jbNovoUsuario;
    private javax.swing.JButton jbPesquisarUsuario;
    private javax.swing.JButton jbSalvarUsuario;
    private javax.swing.JComboBox<String> jcTipoUsuario;
    private javax.swing.JTextField jtCadastroUsuario;
    private javax.swing.JPasswordField jtConfirmaSenha;
    private javax.swing.JTextField jtIDCadastroUser;
    private javax.swing.JTextField jtPesquisaUsuario;
    private javax.swing.JPasswordField jtSenhaUsuario;
    // End of variables declaration//GEN-END:variables
}
