/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.ConexaoDB;
import controler.ControleBebida;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.ModelBebida;
import model.ModelTable;

/**
 *
 * @author renato
 */
public class CadastroProduto extends javax.swing.JFrame {

    ControleBebida dao = new ControleBebida();
    ModelBebida mod = new ModelBebida();
        ConexaoDB conecta = new ConexaoDB();//variavel global
    
    int flag = 0;
    public CadastroProduto() {
        initComponents();
        preencherTabela("select *from bebidas order by quantidade_bebida");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JtabelaPedido = new javax.swing.JTabbedPane();
        jPanelBebida = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jCselBebida = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtQuantidadeBebida = new javax.swing.JTextField();
        jCancelarProdutoBebida = new javax.swing.JButton();
        jSalvarProdutoBebida = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProdutoBebida = new javax.swing.JTable();
        jExcluirProdutoBebida = new javax.swing.JButton();
        jVoltarProdutoBebida = new javax.swing.JButton();
        jEditarProdutoBebida = new javax.swing.JButton();
        jbNovoBebidas = new javax.swing.JButton();
        jbPesquisaBebida = new javax.swing.JButton();
        jtPesquisaBebida = new javax.swing.JTextField();
        jtIDBebida = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanelSobremesa = new javax.swing.JPanel();
        jCselSobremesa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtQuantidadeSobremesa = new javax.swing.JTextField();
        jCancelarProdutoSobremesa = new javax.swing.JButton();
        jSalvarProdutoSobremesa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutoSobremesa = new javax.swing.JTable();
        jExcluirProdutoSobremesa = new javax.swing.JButton();
        jVoltarProdutoSobremesa = new javax.swing.JButton();
        jEditarProdutoSobremesa = new javax.swing.JButton();
        jPanelComida = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCselComida = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtQuantidadeComida = new javax.swing.JTextField();
        jCancelarProdutoComida = new javax.swing.JButton();
        jSalvarProdutoComida = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProdutoComida = new javax.swing.JTable();
        jExcluirProdutoComida = new javax.swing.JButton();
        jVoltarProdutoComida = new javax.swing.JButton();
        jEditarProdutoComida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Produto");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Tipo de Bebida:");

        jCselBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coca-Cola\t", "Suquinho de maça", "Itubaína", " " }));
        jCselBebida.setEnabled(false);
        jCselBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCselBebidaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Quantidade:");

        jtQuantidadeBebida.setEnabled(false);
        jtQuantidadeBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtQuantidadeBebidaActionPerformed(evt);
            }
        });

        jCancelarProdutoBebida.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jCancelarProdutoBebida.setText("Cancelar");
        jCancelarProdutoBebida.setEnabled(false);
        jCancelarProdutoBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarProdutoBebidaActionPerformed(evt);
            }
        });

        jSalvarProdutoBebida.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jSalvarProdutoBebida.setText("Salvar");
        jSalvarProdutoBebida.setEnabled(false);
        jSalvarProdutoBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarProdutoBebidaActionPerformed(evt);
            }
        });

        jTableProdutoBebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProdutoBebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutoBebidaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProdutoBebida);

        jExcluirProdutoBebida.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jExcluirProdutoBebida.setText("Excluir");
        jExcluirProdutoBebida.setEnabled(false);
        jExcluirProdutoBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirProdutoBebidaActionPerformed(evt);
            }
        });

        jVoltarProdutoBebida.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jVoltarProdutoBebida.setText("Voltar");
        jVoltarProdutoBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarProdutoBebidaActionPerformed(evt);
            }
        });

        jEditarProdutoBebida.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jEditarProdutoBebida.setText("Editar");
        jEditarProdutoBebida.setEnabled(false);
        jEditarProdutoBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarProdutoBebidaActionPerformed(evt);
            }
        });

        jbNovoBebidas.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jbNovoBebidas.setText("Novo ");
        jbNovoBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoBebidasActionPerformed(evt);
            }
        });

        jbPesquisaBebida.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jbPesquisaBebida.setText("Pesquisar");
        jbPesquisaBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaBebidaActionPerformed(evt);
            }
        });

        jtIDBebida.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("ID:");

        javax.swing.GroupLayout jPanelBebidaLayout = new javax.swing.GroupLayout(jPanelBebida);
        jPanelBebida.setLayout(jPanelBebidaLayout);
        jPanelBebidaLayout.setHorizontalGroup(
            jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBebidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBebidaLayout.createSequentialGroup()
                        .addComponent(jbNovoBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBebidaLayout.createSequentialGroup()
                        .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanelBebidaLayout.createSequentialGroup()
                                .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCselBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelBebidaLayout.createSequentialGroup()
                                        .addComponent(jtQuantidadeBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtIDBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelBebidaLayout.createSequentialGroup()
                                .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelBebidaLayout.createSequentialGroup()
                                        .addComponent(jCancelarProdutoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jExcluirProdutoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jEditarProdutoBebida, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jVoltarProdutoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtPesquisaBebida))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbPesquisaBebida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSalvarProdutoBebida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                        .addGap(43, 43, 43))))
        );
        jPanelBebidaLayout.setVerticalGroup(
            jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBebidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNovoBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCselBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtQuantidadeBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtIDBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancelarProdutoBebida)
                    .addComponent(jSalvarProdutoBebida)
                    .addComponent(jExcluirProdutoBebida)
                    .addComponent(jVoltarProdutoBebida)
                    .addComponent(jEditarProdutoBebida))
                .addGap(43, 43, 43)
                .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPesquisaBebida)
                    .addComponent(jtPesquisaBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        JtabelaPedido.addTab("Bebida", jPanelBebida);

        jCselSobremesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Sobremesa", "Pudim\t", "Casadin\t", "Beijinho", " " }));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Tipo de Sobremesa:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Quantidade:");

        jtQuantidadeSobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtQuantidadeSobremesaActionPerformed(evt);
            }
        });

        jCancelarProdutoSobremesa.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jCancelarProdutoSobremesa.setText("Cancelar");

        jSalvarProdutoSobremesa.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jSalvarProdutoSobremesa.setText("Salvar");

        jTableProdutoSobremesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableProdutoSobremesa);

        jExcluirProdutoSobremesa.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jExcluirProdutoSobremesa.setText("Excluir");

        jVoltarProdutoSobremesa.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jVoltarProdutoSobremesa.setText("Voltar");
        jVoltarProdutoSobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarProdutoSobremesaActionPerformed(evt);
            }
        });

        jEditarProdutoSobremesa.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jEditarProdutoSobremesa.setText("Editar");
        jEditarProdutoSobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarProdutoSobremesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSobremesaLayout = new javax.swing.GroupLayout(jPanelSobremesa);
        jPanelSobremesa.setLayout(jPanelSobremesaLayout);
        jPanelSobremesaLayout.setHorizontalGroup(
            jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSobremesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelSobremesaLayout.createSequentialGroup()
                        .addComponent(jCancelarProdutoSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jExcluirProdutoSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jEditarProdutoSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jVoltarProdutoSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSalvarProdutoSobremesa, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                    .addGroup(jPanelSobremesaLayout.createSequentialGroup()
                        .addGroup(jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCselSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtQuantidadeSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );
        jPanelSobremesaLayout.setVerticalGroup(
            jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSobremesaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCselSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(54, 54, 54)
                .addGroup(jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtQuantidadeSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancelarProdutoSobremesa)
                    .addComponent(jSalvarProdutoSobremesa)
                    .addComponent(jExcluirProdutoSobremesa)
                    .addComponent(jVoltarProdutoSobremesa)
                    .addComponent(jEditarProdutoSobremesa))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        JtabelaPedido.addTab("Sobremesa", jPanelSobremesa);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Tipo de Comida:");

        jCselComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Comida", "X-Burgão", "X-Bacon", "X-Denovo" }));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Quantidade:");

        jtQuantidadeComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtQuantidadeComidaActionPerformed(evt);
            }
        });

        jCancelarProdutoComida.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jCancelarProdutoComida.setText("Cancelar");

        jSalvarProdutoComida.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jSalvarProdutoComida.setText("Salvar");

        jTableProdutoComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableProdutoComida);

        jExcluirProdutoComida.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jExcluirProdutoComida.setText("Excluir");

        jVoltarProdutoComida.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jVoltarProdutoComida.setText("Voltar");
        jVoltarProdutoComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarProdutoComidaActionPerformed(evt);
            }
        });

        jEditarProdutoComida.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jEditarProdutoComida.setText("Editar");
        jEditarProdutoComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarProdutoComidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelComidaLayout = new javax.swing.GroupLayout(jPanelComida);
        jPanelComida.setLayout(jPanelComidaLayout);
        jPanelComidaLayout.setHorizontalGroup(
            jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComidaLayout.createSequentialGroup()
                        .addComponent(jCancelarProdutoComida, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jExcluirProdutoComida, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jEditarProdutoComida, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jVoltarProdutoComida, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSalvarProdutoComida, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelComidaLayout.createSequentialGroup()
                        .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCselComida, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtQuantidadeComida, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
        );
        jPanelComidaLayout.setVerticalGroup(
            jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCselComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtQuantidadeComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jExcluirProdutoComida)
                        .addComponent(jVoltarProdutoComida)
                        .addComponent(jEditarProdutoComida))
                    .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCancelarProdutoComida)
                        .addComponent(jSalvarProdutoComida)))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        JtabelaPedido.addTab("Comida", jPanelComida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JtabelaPedido)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JtabelaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(573, 531));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtQuantidadeSobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtQuantidadeSobremesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtQuantidadeSobremesaActionPerformed

    private void jtQuantidadeComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtQuantidadeComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtQuantidadeComidaActionPerformed

    private void jtQuantidadeBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtQuantidadeBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtQuantidadeBebidaActionPerformed

    private void jVoltarProdutoSobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarProdutoSobremesaActionPerformed
          TelaPrincipal telacad = new TelaPrincipal();
      
        telacad.setVisible(true);
    }//GEN-LAST:event_jVoltarProdutoSobremesaActionPerformed

    private void jVoltarProdutoBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarProdutoBebidaActionPerformed
         TelaPrincipal telacad = new TelaPrincipal();
      
        telacad.setVisible(true);
    }//GEN-LAST:event_jVoltarProdutoBebidaActionPerformed

    private void jVoltarProdutoComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarProdutoComidaActionPerformed
         TelaPrincipal telacad = new TelaPrincipal();
      
        telacad.setVisible(true);
    }//GEN-LAST:event_jVoltarProdutoComidaActionPerformed

    private void jEditarProdutoComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarProdutoComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditarProdutoComidaActionPerformed

    private void jEditarProdutoSobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarProdutoSobremesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditarProdutoSobremesaActionPerformed

    private void jSalvarProdutoBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarProdutoBebidaActionPerformed
       
if(jtQuantidadeBebida.getText().isEmpty()){

    JOptionPane.showMessageDialog(null, "Preencha a Quantidade para continuar");
    
    jtQuantidadeBebida.requestFocus();//vai direto para nome


}else       
        
if(flag == 1){//update com dados alterados
        mod.setTipoBebida((String)jCselBebida.getSelectedItem());
        mod.setQuantBebida(Integer.parseInt(jtQuantidadeBebida.getText()));
       
        dao.Salvar(mod);
       //limpa as areas de texto:
        jtQuantidadeBebida.setText("");
       
        
        //bloqueia areas de texto:
        jCselBebida.setEnabled(false);
        jtQuantidadeBebida.setEnabled(false);
        jEditarProdutoBebida.setEnabled(true);
        jExcluirProdutoBebida.setEnabled(true);
        
        preencherTabela("select *from bebidas order by tipo_bebida");
        
}  else{
     mod.setTipoBebida((String)jCselBebida.getSelectedItem());
        mod.setQuantBebida(Integer.parseInt(jtQuantidadeBebida.getText()));
       
        dao.Alterar(mod);
        
        jtQuantidadeBebida.setText("");
       
        
        //bloqueia areas de texto:
        jCselBebida.setEnabled(false);
        jtQuantidadeBebida.setEnabled(false);
        jEditarProdutoBebida.setEnabled(true);
        jExcluirProdutoBebida.setEnabled(true);
        
            preencherTabela("select *from bebidas order by tipo_bebida");
    } 
    }//GEN-LAST:event_jSalvarProdutoBebidaActionPerformed

    private void jbNovoBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoBebidasActionPerformed
       
        flag = 1;
        jCselBebida.setEnabled(true);
        jtQuantidadeBebida.setEnabled(true);
        jCancelarProdutoBebida.setEnabled(true);
         jEditarProdutoBebida.setEnabled(false);
         jExcluirProdutoBebida.setEnabled(false);
          jSalvarProdutoBebida.setEnabled(true);
    }//GEN-LAST:event_jbNovoBebidasActionPerformed

    private void jCancelarProdutoBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarProdutoBebidaActionPerformed
        jCselBebida.setEnabled(false);
        jtQuantidadeBebida.setEnabled(false);
        jCancelarProdutoBebida.setEnabled(false);
         jEditarProdutoBebida.setEnabled(false);
         jExcluirProdutoBebida.setEnabled(false);
          jSalvarProdutoBebida.setEnabled(false);
    }//GEN-LAST:event_jCancelarProdutoBebidaActionPerformed

    private void jEditarProdutoBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarProdutoBebidaActionPerformed
flag = 2;
        
       jtQuantidadeBebida.setEnabled(true);
       jSalvarProdutoBebida.setEnabled(true);
     // preencherTabela("select *from bebidas order by quantidade_bebida");
       jCselBebida.setEnabled(true);
       
    }//GEN-LAST:event_jEditarProdutoBebidaActionPerformed

    private void jTableProdutoBebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoBebidaMouseClicked
        
         String tipo_bebida ="" + jTableProdutoBebida.getValueAt(jTableProdutoBebida.getSelectedRow(), 1);//pega valores da tabela;
               conecta.conexao();
               conecta.executaSql("select *from bebidas where tipo_bebida='" + tipo_bebida +"'");   
        
        try {
              
               conecta.rs.first();
               jtIDBebida.setText(String.valueOf(conecta.rs.getInt("cod_bebida")));
               jCselBebida.setSelectedItem(conecta.rs.getString("tipo_bebida"));
               jtQuantidadeBebida.setText(String.valueOf(conecta.rs.getInt("quantidade_bebida")));
               
               
               
               
           } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, "Erro ao selecionar dados" + ex);
           }

conecta.desconecta();
jEditarProdutoBebida.setEnabled(true);
jExcluirProdutoBebida.setEnabled(true);

   
    }//GEN-LAST:event_jTableProdutoBebidaMouseClicked

    private void jCselBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCselBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCselBebidaActionPerformed

    private void jbPesquisaBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaBebidaActionPerformed
        mod.setPesquisaBebida(jtPesquisaBebida.getText());
        ModelBebida model = dao.buscaBebida(mod);//envia por parametro o que o usuario digitou
        jCselBebida.setSelectedItem(model.getTipoBebida());
        jtQuantidadeBebida.setText(String.valueOf(model.getQuantBebida()));
        jtIDBebida.setText(String.valueOf(model.getCodBebida()));
         
    }//GEN-LAST:event_jbPesquisaBebidaActionPerformed

    private void jExcluirProdutoBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirProdutoBebidaActionPerformed
       // JOptionPane.showMessageDialog(null,"Escolha o que deseja  Excluir");
        
        int resposta = 0;//guarda resposta do usuario
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente Excluir ?");
        
       if(resposta == JOptionPane.YES_OPTION){
           mod.setCodBebida(Integer.parseInt(jtIDBebida.getText()));
            dao.Excluir(mod);
        preencherTabela("select *from bebidas order by tipo_bebida");
        
        jtQuantidadeBebida.setText("");
        jtIDBebida.setText("");
        }
        
    }//GEN-LAST:event_jExcluirProdutoBebidaActionPerformed

        public void preencherTabela(String Sql){
       ArrayList dados = new ArrayList();
       String [] colunas = new String []{"ID","Tipo de Bebida","Quantidade"};
        conecta.conexao();
        conecta.executaSql(Sql);
        
        try{
            conecta.rs.first();
            do{
                dados.add(new Object[]{conecta.rs.getInt("cod_bebida"),conecta.rs.getString("tipo_bebida"),conecta.rs.getInt("quantidade_bebida")});
            }while(conecta.rs.next());
        }catch (SQLException ex){
           JOptionPane.showMessageDialog(rootPane,"Busque Novamente "); 
        }
        ModelTable modelo = new ModelTable(dados, colunas);
        jTableProdutoBebida.setModel(modelo);
        jTableProdutoBebida.getColumnModel().getColumn(0).setPreferredWidth(67);
        jTableProdutoBebida.getColumnModel().getColumn(0).setResizable(false);//usuario n pode aumentar tamanho da coluna
        
        jTableProdutoBebida.getColumnModel().getColumn(1).setPreferredWidth(330);
        jTableProdutoBebida.getColumnModel().getColumn(1).setResizable(false);//usuario n pode aumentar nome na coluna
       
        jTableProdutoBebida.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableProdutoBebida.getColumnModel().getColumn(2).setResizable(false);//usuario n pode aumentar telefone da coluna
       
        //jTableProdutoBebida.getColumnModel().getColumn(3).setPreferredWidth(220);
        //jTableProdutoBebida.getColumnModel().getColumn(3).setResizable(false);//usuario n pode aumentar endereco da coluna
       
        jTableProdutoBebida.getTableHeader().setReorderingAllowed(false);
        jTableProdutoBebida.setAutoResizeMode(jTableProdutoBebida.AUTO_RESIZE_OFF);//nao pode redimencionar tabela;
        
        jTableProdutoBebida.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//seleciona apenas um por vez na tabela
        
        
        conecta.desconecta();
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JtabelaPedido;
    private javax.swing.JButton jCancelarProdutoBebida;
    private javax.swing.JButton jCancelarProdutoComida;
    private javax.swing.JButton jCancelarProdutoSobremesa;
    private javax.swing.JComboBox<String> jCselBebida;
    private javax.swing.JComboBox<String> jCselComida;
    private javax.swing.JComboBox<String> jCselSobremesa;
    private javax.swing.JButton jEditarProdutoBebida;
    private javax.swing.JButton jEditarProdutoComida;
    private javax.swing.JButton jEditarProdutoSobremesa;
    private javax.swing.JButton jExcluirProdutoBebida;
    private javax.swing.JButton jExcluirProdutoComida;
    private javax.swing.JButton jExcluirProdutoSobremesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelBebida;
    private javax.swing.JPanel jPanelComida;
    private javax.swing.JPanel jPanelSobremesa;
    private javax.swing.JButton jSalvarProdutoBebida;
    private javax.swing.JButton jSalvarProdutoComida;
    private javax.swing.JButton jSalvarProdutoSobremesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableProdutoBebida;
    private javax.swing.JTable jTableProdutoComida;
    private javax.swing.JTable jTableProdutoSobremesa;
    private javax.swing.JButton jVoltarProdutoBebida;
    private javax.swing.JButton jVoltarProdutoComida;
    private javax.swing.JButton jVoltarProdutoSobremesa;
    private javax.swing.JButton jbNovoBebidas;
    private javax.swing.JButton jbPesquisaBebida;
    private javax.swing.JTextField jtIDBebida;
    private javax.swing.JTextField jtPesquisaBebida;
    private javax.swing.JTextField jtQuantidadeBebida;
    private javax.swing.JTextField jtQuantidadeComida;
    private javax.swing.JTextField jtQuantidadeSobremesa;
    // End of variables declaration//GEN-END:variables

   // private void preencherTabela(String select_from_bebidas_order_by_tipo_bebida) {
     //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   // }
}
