/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.ModelPedidos;

/**
 *
 * @author renato
 */
public class Pedido extends javax.swing.JInternalFrame {

    ModelPedidos ped = new ModelPedidos();
    
    double [] comida = new double[3];
    double [] bebida = new double[3];
    double [] sobremesa = new double[3];
    //double tot = comida[0]+comida[1]+comida[2];
    public Pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelComida = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbXBurgao = new javax.swing.JCheckBox();
        jcbXBacon = new javax.swing.JCheckBox();
        jcbXDenovo = new javax.swing.JCheckBox();
        jtXBurgao = new javax.swing.JTextField();
        jtXBacon = new javax.swing.JTextField();
        jtXDenovo = new javax.swing.JTextField();
        jPanelBebida = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcbCoca = new javax.swing.JCheckBox();
        jcbSuco = new javax.swing.JCheckBox();
        jcbItubaina = new javax.swing.JCheckBox();
        jtCocaCola = new javax.swing.JTextField();
        jtSuco = new javax.swing.JTextField();
        jtItubaina = new javax.swing.JTextField();
        jPanelSobremesa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcbPudim = new javax.swing.JCheckBox();
        jcbCasadinho = new javax.swing.JCheckBox();
        jcbBeijinho = new javax.swing.JCheckBox();
        jtPudim = new javax.swing.JTextField();
        jtCasadinho = new javax.swing.JTextField();
        jtBeijinho = new javax.swing.JTextField();
        jPanelBebida1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtTotalComida = new javax.swing.JTextField();
        jtTotalSobre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtTotalBebida = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcbPagamento = new javax.swing.JComboBox<>();
        jbTotal = new javax.swing.JButton();
        jbReiniciar = new javax.swing.JButton();
        jbFinalizarPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtrecibo = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Pedido");
        setName("Pedido"); // NOI18N

        jPanelComida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Comida");

        jcbXBurgao.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jcbXBurgao.setText("X-Burgão");
        jcbXBurgao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbXBurgaoActionPerformed(evt);
            }
        });

        jcbXBacon.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jcbXBacon.setText("X-Bacon");
        jcbXBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbXBaconActionPerformed(evt);
            }
        });

        jcbXDenovo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jcbXDenovo.setText("X-Denovo");
        jcbXDenovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbXDenovoActionPerformed(evt);
            }
        });

        jtXBurgao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtXBacon.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtXDenovo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanelComidaLayout = new javax.swing.GroupLayout(jPanelComida);
        jPanelComida.setLayout(jPanelComidaLayout);
        jPanelComidaLayout.setHorizontalGroup(
            jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaLayout.createSequentialGroup()
                .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelComidaLayout.createSequentialGroup()
                                .addComponent(jcbXBurgao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtXBurgao, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelComidaLayout.createSequentialGroup()
                                .addComponent(jcbXBacon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtXBacon, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelComidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jcbXDenovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtXDenovo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanelComidaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelComidaLayout.setVerticalGroup(
            jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbXBurgao)
                    .addComponent(jtXBurgao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbXBacon)
                    .addComponent(jtXBacon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbXDenovo)
                    .addComponent(jtXDenovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanelBebida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Bebida");

        jcbCoca.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jcbCoca.setText("Coca-Cola");
        jcbCoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCocaActionPerformed(evt);
            }
        });

        jcbSuco.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jcbSuco.setText("Suco Maçã");
        jcbSuco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSucoActionPerformed(evt);
            }
        });

        jcbItubaina.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jcbItubaina.setText("Itubaína");
        jcbItubaina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbItubainaActionPerformed(evt);
            }
        });

        jtCocaCola.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtSuco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtItubaina.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanelBebidaLayout = new javax.swing.GroupLayout(jPanelBebida);
        jPanelBebida.setLayout(jPanelBebidaLayout);
        jPanelBebidaLayout.setHorizontalGroup(
            jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBebidaLayout.createSequentialGroup()
                .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBebidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBebidaLayout.createSequentialGroup()
                                .addComponent(jcbCoca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtCocaCola, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBebidaLayout.createSequentialGroup()
                                .addComponent(jcbSuco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtSuco, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelBebidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jcbItubaina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtItubaina, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanelBebidaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBebidaLayout.setVerticalGroup(
            jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBebidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCoca)
                    .addComponent(jtCocaCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSuco)
                    .addComponent(jtSuco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbItubaina)
                    .addComponent(jtItubaina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSobremesa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Sobremesa");

        jcbPudim.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jcbPudim.setText("Pudim");
        jcbPudim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPudimActionPerformed(evt);
            }
        });

        jcbCasadinho.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jcbCasadinho.setText("Casadinho");
        jcbCasadinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCasadinhoActionPerformed(evt);
            }
        });

        jcbBeijinho.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jcbBeijinho.setText("Beijinho");
        jcbBeijinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBeijinhoActionPerformed(evt);
            }
        });

        jtPudim.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtCasadinho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtBeijinho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanelSobremesaLayout = new javax.swing.GroupLayout(jPanelSobremesa);
        jPanelSobremesa.setLayout(jPanelSobremesaLayout);
        jPanelSobremesaLayout.setHorizontalGroup(
            jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSobremesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSobremesaLayout.createSequentialGroup()
                        .addComponent(jcbPudim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtPudim, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSobremesaLayout.createSequentialGroup()
                        .addComponent(jcbCasadinho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jtCasadinho, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSobremesaLayout.createSequentialGroup()
                        .addComponent(jcbBeijinho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtBeijinho, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanelSobremesaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSobremesaLayout.setVerticalGroup(
            jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSobremesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbPudim)
                    .addComponent(jtPudim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCasadinho)
                    .addComponent(jtCasadinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSobremesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbBeijinho)
                    .addComponent(jtBeijinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanelBebida1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Pedido");

        jtTotalComida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtTotalSobre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("Total Comida:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("Total Bebida:");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setText("Total Sobremesa:");

        jtTotalBebida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setText("Total :");

        jtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel10.setText("Pagamento:");

        jcbPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão" }));

        javax.swing.GroupLayout jPanelBebida1Layout = new javax.swing.GroupLayout(jPanelBebida1);
        jPanelBebida1.setLayout(jPanelBebida1Layout);
        jPanelBebida1Layout.setHorizontalGroup(
            jPanelBebida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBebida1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelBebida1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBebida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBebida1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtTotalComida, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBebida1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtTotalBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBebida1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtTotalSobre))
                    .addGroup(jPanelBebida1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBebida1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jcbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBebida1Layout.setVerticalGroup(
            jPanelBebida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBebida1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBebida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtTotalComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanelBebida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtTotalSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(jPanelBebida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtTotalBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBebida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanelBebida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jbTotal.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbTotal.setText("Total");
        jbTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTotalActionPerformed(evt);
            }
        });

        jbReiniciar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbReiniciar.setText("Reiniciar");
        jbReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReiniciarActionPerformed(evt);
            }
        });

        jbFinalizarPedido.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbFinalizarPedido.setText("Finalizar Pedido");
        jbFinalizarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbFinalizarPedidoMouseClicked(evt);
            }
        });
        jbFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFinalizarPedidoActionPerformed(evt);
            }
        });

        jtrecibo.setColumns(20);
        jtrecibo.setRows(5);
        jScrollPane1.setViewportView(jtrecibo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelSobremesa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelComida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFinalizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBebida1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbTotal)
                                    .addComponent(jbReiniciar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbFinalizarPedido))
                            .addComponent(jPanelBebida1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbXBurgaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbXBurgaoActionPerformed
         double cXburgao = Double.parseDouble(jtXBurgao.getText());
        double Xburgao = Double.parseDouble(jtXBurgao.getText());
        double iXburgao = 7.50;
        
      if (jcbXBurgao.isSelected())
      {
            
         comida[0] = ((Xburgao * iXburgao) );
          String pMael = String.format("R$ %.2f", comida[0]);
          jtXBurgao.setText(pMael);
         
      }
    }//GEN-LAST:event_jcbXBurgaoActionPerformed

    private void jcbXBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbXBaconActionPerformed
        double cXbacon = Double.parseDouble(jtXBacon.getText());
        double Xbacon = Double.parseDouble(jtXBacon.getText());
        double iXbacon = 6.50;
        
      if (jcbXBacon.isSelected())
      {
          
         comida[1] = ((Xbacon * iXbacon) );
          String pMael = String.format("R$ %.2f", comida[1]);
          jtXBacon.setText(pMael);
         
      }
    }//GEN-LAST:event_jcbXBaconActionPerformed

    private void jcbXDenovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbXDenovoActionPerformed
        double cXDenovo = Double.parseDouble(jtXDenovo.getText());
        double XDenovo = Double.parseDouble(jtXDenovo.getText());
        double iXDenovo = 5.00;
        
      if (jcbXDenovo.isSelected())
      {
         
         comida[2] = ((XDenovo * iXDenovo) );
          String pMael = String.format("R$ %.2f", comida[2]);
          jtXDenovo.setText(pMael);
          
      }
    }//GEN-LAST:event_jcbXDenovoActionPerformed

    private void jcbPudimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPudimActionPerformed
        double cPudim = Double.parseDouble(jtPudim.getText());
        double Pudim = Double.parseDouble(jtPudim.getText());
        double iPudim = 3.50;
        
      if (jcbPudim.isSelected())
      {
          
         sobremesa[0] = ((Pudim * iPudim) );
          String pMael = String.format("R$ %.2f", sobremesa[0]);
          jtPudim.setText(pMael);
          
      }
    }//GEN-LAST:event_jcbPudimActionPerformed

    private void jcbCasadinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCasadinhoActionPerformed
        double cCasadinho = Double.parseDouble(jtCasadinho.getText());
        double Casadinho = Double.parseDouble(jtCasadinho.getText());
        double iCasadinho = 2.50;
        
      if (jcbCasadinho.isSelected())
      {
          
         sobremesa[1] = ((Casadinho * iCasadinho) );
          String pMael = String.format("R$ %.2f", sobremesa[1]);
          jtCasadinho.setText(pMael);
          
      }
    }//GEN-LAST:event_jcbCasadinhoActionPerformed

    private void jcbBeijinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBeijinhoActionPerformed
        double cBeijinho = Double.parseDouble(jtBeijinho.getText());
        double Beijinho = Double.parseDouble(jtBeijinho.getText());
        double iBeijinho = 1.50;
        
      if (jcbBeijinho.isSelected())
      {
         
         sobremesa[2] = ((Beijinho * iBeijinho) );
          String pMael = String.format("R$ %.2f", sobremesa[2]);
          jtBeijinho.setText(pMael);
          
      }
    }//GEN-LAST:event_jcbBeijinhoActionPerformed

    private void jbTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTotalActionPerformed
        double sobre = ((sobremesa[0]+sobremesa[1]+sobremesa[2] ));
          String ptotals = String.format("R$ %.2f", sobre);
          
          jtTotalSobre.setText(ptotals);
          //total sobremesa
          double comid = ((comida[0]+comida[1]+comida[2] ));
          String ptotalc = String.format("R$ %.2f", comid);
          
          jtTotalComida.setText(ptotalc);
          //total comida
          double bebid = ((bebida[0]+bebida[1]+bebida[2] ));
          String ptotalb = String.format("R$ %.2f", bebid);
          
          jtTotalBebida.setText(ptotalb);
          //total bebida
          
          
          double total = (sobre + comid + bebid);
          String ptotal = String.format("R$ %.2f",total);
          jtTotal.setText(ptotal);
          
    }//GEN-LAST:event_jbTotalActionPerformed

    private void jcbCocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCocaActionPerformed
        double cCoca = Double.parseDouble(jtCocaCola.getText());
        double Coca = Double.parseDouble(jtCocaCola.getText());
        double iCoca = 4.50;
        
      if (jcbCoca.isSelected())
      {
            
         bebida[0] = ((Coca * iCoca) );
          String pMael = String.format("R$ %.2f", bebida[0]);
          jtCocaCola.setText(pMael);
         
      }
    }//GEN-LAST:event_jcbCocaActionPerformed

    private void jcbSucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSucoActionPerformed
         double cSuco = Double.parseDouble(jtSuco.getText());
        double Suco = Double.parseDouble(jtSuco.getText());
        double iSuco = 5.50;
        
      if (jcbSuco.isSelected())
      {
            
         bebida[1] = ((Suco * iSuco) );
          String pMael = String.format("R$ %.2f", bebida[1]);
          jtSuco.setText(pMael);
         
      }
    }//GEN-LAST:event_jcbSucoActionPerformed

    private void jcbItubainaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbItubainaActionPerformed
         double cItub = Double.parseDouble(jtItubaina.getText());
        double Itub = Double.parseDouble(jtItubaina.getText());
        double iItub = 6.50;
        
      if (jcbItubaina.isSelected())
      {
            
         bebida[2] = ((Itub * iItub) );
          String pMael = String.format("R$ %.2f", bebida[2]);
          jtItubaina.setText(pMael);
         
      }
    }//GEN-LAST:event_jcbItubainaActionPerformed

    private void jbReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReiniciarActionPerformed
       jtXBurgao.setText("");
        jtXBacon.setText("");      //limpa area de comida
         jtXDenovo.setText("");
         
        jtBeijinho.setText("");
         jtCasadinho.setText("");   //limpa area de sobremesa
           jtPudim.setText("");
           
          jtCocaCola.setText("");
           jtSuco.setText("");      //limpa area de bebida
             jtItubaina.setText("");
             
          jtTotal.setText("");
           jtTotalBebida.setText(""); //limpa area de valor total
           jtTotalComida.setText("");
           jtTotalSobre.setText("");
           
    }//GEN-LAST:event_jbReiniciarActionPerformed

    private void jbFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFinalizarPedidoActionPerformed
  /*comida[0] = Double.parseDouble(jtXBurgao.getText());
       comida[1] = Double.parseDouble(jtXBacon.getText());
       comida[2] = Double.parseDouble(jtXDenovo.getText());
       
       bebida[0] = Double.parseDouble(jtCocaCola.getText());
       bebida[1] = Double.parseDouble(jtSuco.getText());
       bebida[2] = Double.parseDouble(jtItubaina.getText());
      
       sobremesa[0] = Double.parseDouble(jtPudim.getText());
       sobremesa[1] = Double.parseDouble(jtCasadinho.getText());
       sobremesa[2] = Double.parseDouble(jtBeijinho.getText());*/
      jtrecibo.append(" \t\nTô com Fome, quero mais Systems:\n\n"+
              "X-Burgão:\t\t" + comida[0] +
              "\nX-Bacon:\t\t" + comida[1] +
              "\nX-Denovo:\t\t" + comida[2] +
              "\n===========================" +
              "\nCoca-Cola:\t\t" + bebida[0] +
              "\nSuco de Maçã:\t" + bebida[1] +
              "\nItubaína:\t\t" + bebida[2] +
              "\n===========================" +
              "\nPudim:\t\t" + sobremesa[0]+
              "\nCasadinho:\t\t" + sobremesa[1] +
              "\nBeijinho:\t\t" + sobremesa[2]+
              "\n==========================="+
              "\nTotal:\t\t"+ jtTotal.getText()+
              "\nForma Pagamento:\t"+ jcbPagamento.getSelectedItem()
              
              );
        
         
    }//GEN-LAST:event_jbFinalizarPedidoActionPerformed

    private void jbFinalizarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizarPedidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbFinalizarPedidoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelBebida;
    private javax.swing.JPanel jPanelBebida1;
    private javax.swing.JPanel jPanelComida;
    private javax.swing.JPanel jPanelSobremesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbFinalizarPedido;
    private javax.swing.JButton jbReiniciar;
    private javax.swing.JButton jbTotal;
    private javax.swing.JCheckBox jcbBeijinho;
    private javax.swing.JCheckBox jcbCasadinho;
    private javax.swing.JCheckBox jcbCoca;
    private javax.swing.JCheckBox jcbItubaina;
    private javax.swing.JComboBox<String> jcbPagamento;
    private javax.swing.JCheckBox jcbPudim;
    private javax.swing.JCheckBox jcbSuco;
    private javax.swing.JCheckBox jcbXBacon;
    private javax.swing.JCheckBox jcbXBurgao;
    private javax.swing.JCheckBox jcbXDenovo;
    private javax.swing.JTextField jtBeijinho;
    private javax.swing.JTextField jtCasadinho;
    private javax.swing.JTextField jtCocaCola;
    private javax.swing.JTextField jtItubaina;
    private javax.swing.JTextField jtPudim;
    private javax.swing.JTextField jtSuco;
    private javax.swing.JTextField jtTotal;
    private javax.swing.JTextField jtTotalBebida;
    private javax.swing.JTextField jtTotalComida;
    private javax.swing.JTextField jtTotalSobre;
    private javax.swing.JTextField jtXBacon;
    private javax.swing.JTextField jtXBurgao;
    private javax.swing.JTextField jtXDenovo;
    private javax.swing.JTextArea jtrecibo;
    // End of variables declaration//GEN-END:variables
}
