/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.ConexaoDB;

/**
 *
 * @author renato
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoDB conecta = new ConexaoDB();
    
    public TelaPrincipal() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmCadastroCliente = new javax.swing.JMenuItem();
        jmCadastroProduto = new javax.swing.JMenuItem();
        jmcadastrousuario = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();
        jmSairTela = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmCadastro.setText("Cadastro");

        jmCadastroCliente.setText("Cliente");
        jmCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroClienteActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadastroCliente);

        jmCadastroProduto.setText("Produto");
        jmCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroProdutoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadastroProduto);

        jmcadastrousuario.setText("Usuário");
        jmcadastrousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcadastrousuarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmcadastrousuario);

        jMenuBar1.add(jmCadastro);

        jmSair.setText("Sair");

        jmSairTela.setText("Sair");
        jmSairTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairTelaActionPerformed(evt);
            }
        });
        jmSair.add(jmSairTela);

        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroClienteActionPerformed
        CadastroCliente telacad = new CadastroCliente();
        jdpPrincipal.add(telacad);
        telacad.setVisible(true);
        
        
    }//GEN-LAST:event_jmCadastroClienteActionPerformed

    private void jmSairTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairTelaActionPerformed
       conecta.desconecta();
       System.exit(0);
    }//GEN-LAST:event_jmSairTelaActionPerformed

    private void jmcadastrousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcadastrousuarioActionPerformed
       
      CadastroUsuario tela = new CadastroUsuario();
        tela.setVisible(true);
    }//GEN-LAST:event_jmcadastrousuarioActionPerformed

    private void jmCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroProdutoActionPerformed
         CadastroProduto telacad = new CadastroProduto();
      
        telacad.setVisible(true);
        
    }//GEN-LAST:event_jmCadastroProdutoActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenuItem jmCadastroCliente;
    private javax.swing.JMenuItem jmCadastroProduto;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmSairTela;
    private javax.swing.JMenuItem jmcadastrousuario;
    // End of variables declaration//GEN-END:variables
}
